default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bazzar_development

test:
  <<: *default
  database: bazzar_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: bazzar_production
  username: bazzar
  password: <%= ENV["BAZZAR_DATABASE_PASSWORD"] %>
