default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: push_development

test:
  <<: *default
  database: push_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: push_production
  username: push
  password: <%= ENV["PUSH_DATABASE_PASSWORD"] %>
